#!/usr/bin/env php
<?php

use IlluminateFoundationApplication;
use SymfonyComponentConsoleInputArgvInput;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
