const express=require('express');const cors=require('cors');const dotenv=require('dotenv');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const Database=require('better-sqlite3');const {randomUUID}=require('crypto');
dotenv.config();const app=express();if(process.env.NODE_ENV==='production' && (!process.env.JWT_SECRET || process.env.JWT_SECRET.length<32)) throw new Error('JWT_SECRET must be at least 32 characters in production');app.use(cors({origin: process.env.CORS_ORIGIN ? process.env.CORS_ORIGIN.split(',').map(x=>x.trim()) : true}));app.use(express.json({limit:'12mb'}));
const db=new Database(process.env.DB_PATH||'kurdistan-tourism.db');db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT,email TEXT UNIQUE,password TEXT,role TEXT DEFAULT 'user',created_at TEXT);CREATE TABLE IF NOT EXISTS locations(id TEXT PRIMARY KEY,name TEXT,description TEXT,category TEXT,lat REAL,lng REAL,rating REAL DEFAULT 0,image TEXT,verified INTEGER DEFAULT 1,created_at TEXT);CREATE TABLE IF NOT EXISTS accommodations(id TEXT PRIMARY KEY,name TEXT,city TEXT,price REAL,rating REAL DEFAULT 0,image TEXT,created_at TEXT);CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY,user_id TEXT,accommodation_id TEXT,date TEXT,nights INTEGER,total REAL,guests INTEGER DEFAULT 1,status TEXT DEFAULT 'pending',payment_status TEXT DEFAULT 'unpaid',created_at TEXT);CREATE TABLE IF NOT EXISTS reviews(id TEXT PRIMARY KEY,user_id TEXT,location_id TEXT,rating INTEGER,comment TEXT,created_at TEXT);CREATE TABLE IF NOT EXISTS favorites(user_id TEXT,location_id TEXT,PRIMARY KEY(user_id,location_id));`);
try { db.exec("ALTER TABLE bookings ADD COLUMN guests INTEGER DEFAULT 1"); } catch (_) {}
const now=()=>new Date().toISOString();const withImages=x=>{let images=[];try{images=JSON.parse(x.images||'[]')}catch(_){}return {...x,images}};
if(!db.prepare('SELECT 1 FROM users WHERE email=?').get(process.env.ADMIN_EMAIL||'admin@kurdistantourism.local')){const p=bcrypt.hashSync(process.env.ADMIN_PASSWORD||'ChangeMe123!',10);db.prepare('INSERT INTO users(id,name,email,password,role,created_at) VALUES(?,?,?,?,?,?)').run(randomUUID(),'Administrator',process.env.ADMIN_EMAIL||'admin@kurdistantourism.local',p,'admin',now());}
if(db.prepare('SELECT count(*) c FROM locations').get().c===0){const rows=[['Dukan Lake','Beautiful lake and mountain destination.','lake',35.946,44.954,4.8,''],['Rawanduz','Mountain valley and canyon destination.','mountain',36.617,44.536,4.9,''],['Bekhal Waterfall','Popular waterfall near Rawanduz.','waterfall',36.595,44.457,4.7,''],['Shanidar Cave','Historic archaeological cave.','cave',36.837,44.225,4.6,''],['Erbil Citadel','Historic UNESCO World Heritage site.','heritage',36.191,44.009,4.8,'']];const s=db.prepare('INSERT INTO locations VALUES(?,?,?,?,?,?,?,?,?,?)');for(const r of rows)s.run(randomUUID(),r[0],r[1],r[2],r[3],r[4],r[5],r[6],1,now());}
if(db.prepare('SELECT count(*) c FROM accommodations').get().c===0){const rows=[['Erbil International Hotel','Erbil',120,4.7,''],['Grand Millennium Sulaimani','Sulaymaniyah',150,4.8,''],['Rawanduz Mountain Lodge','Rawanduz',75,4.6,''],['Dukan Lake Resort','Dukan',90,4.5,'']];const s=db.prepare('INSERT INTO accommodations VALUES(?,?,?,?,?,?,?)');for(const r of rows)s.run(randomUUID(),...r,now());}

require('./admin')(app,db,{auth,admin,now,randomUUID,bcrypt});
function token(u){return jwt.sign({sub:u.id,role:u.role,email:u.email},process.env.JWT_SECRET||'dev-secret',{expiresIn:'30d'})}function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({success:false,message:'Authentication required'});req.user=jwt.verify(h.slice(7),process.env.JWT_SECRET||'dev-secret');const row=db.prepare('SELECT role,banned FROM users WHERE id=?').get(req.user.sub);if(!row||row.banned)return res.status(401).json({success:false,message:'Account disabled'});req.user.role=row.role;next()}catch(e){res.status(401).json({success:false,message:'Invalid token'})}}function admin(req,res,next){if(req.user.role!=='admin')return res.status(403).json({success:false,message:'Admin only'});next()}
app.get('/api/health',(q,s)=>s.json({success:true,status:'online',version:'12.0.0'}));
app.post('/api/auth/register',(q,s)=>{const {name,email,password}=q.body||{};if(!name||!email||!password||password.length<6)return s.status(422).json({success:false,message:'Name, email and password (6+) are required'});try{const u={id:randomUUID(),name,email,password:bcrypt.hashSync(password,10),role:'user',created_at:now()};db.prepare('INSERT INTO users(id,name,email,password,role,created_at) VALUES(?,?,?,?,?,?)').run(u.id,u.name,u.email,u.password,u.role,u.created_at);delete u.password;s.json({success:true,data:{user:u,token:token(u)}})}catch(e){s.status(409).json({success:false,message:'Email already exists'})}});
app.post('/api/auth/login',(q,s)=>{const {email,password}=q.body||{};const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!bcrypt.compareSync(password||'',u.password))return s.status(401).json({success:false,message:'Invalid credentials'});if(u.banned)return s.status(403).json({success:false,message:'Account disabled'});const safe={id:u.id,name:u.name,email:u.email,role:u.role};s.json({success:true,data:{user:safe,token:token(u)}})});
app.get('/api/auth/me',auth,(q,s)=>{const u=db.prepare('SELECT id,name,email,role,created_at FROM users WHERE id=?').get(q.user.sub);s.json({success:true,data:u})});app.post('/api/auth/logout',auth,(q,s)=>s.json({success:true}));
app.get('/api/locations',(q,s)=>{let rows=db.prepare('SELECT * FROM locations WHERE verified=1 ORDER BY rating DESC').all();if(q.query.category)rows=rows.filter(x=>x.category===q.query.category);if(q.query.search){const term=String(q.query.search).toLowerCase();rows=rows.filter(x=>(x.name+' '+x.description+' '+x.category).toLowerCase().includes(term));}const lat=Number(q.query.near_lat),lng=Number(q.query.near_lng),radius=Number(q.query.radius_m||10000);if(Number.isFinite(lat)&&Number.isFinite(lng)&&Number.isFinite(radius)&&radius>0){const R=6371000;const rad=x=>x*Math.PI/180;rows=rows.map(x=>({...x,distance_m:2*R*Math.asin(Math.sqrt(Math.sin((rad(x.lat)-rad(lat))/2)**2+Math.cos(rad(lat))*Math.cos(rad(x.lat))*Math.sin((rad(x.lng)-rad(lng))/2)**2))})).filter(x=>x.distance_m<=radius).sort((a,b)=>a.distance_m-b.distance_m);}s.json({success:true,data:rows.map(withImages)})});
app.get('/api/locations/:id',(q,s)=>{const r=db.prepare('SELECT * FROM locations WHERE id=?').get(q.params.id);r?s.json({success:true,data:withImages(r)}):s.status(404).json({success:false,message:'Location not found'})});
app.post('/api/locations',auth,admin,(q,s)=>{const b=q.body||{},r={id:randomUUID(),name:b.name,description:b.description||'',category:b.category||'other',lat:Number(b.lat),lng:Number(b.lng),rating:Number(b.rating||0),image:b.image||'',verified:Number(b.verified??1),created_at:now()};db.prepare('INSERT INTO locations VALUES(?,?,?,?,?,?,?,?,?,?)').run(...Object.values(r));s.status(201).json({success:true,data:r})});
app.put('/api/locations/:id',auth,admin,(q,s)=>{const b=q.body||{};db.prepare('UPDATE locations SET name=?,description=?,category=?,lat=?,lng=?,rating=?,image=?,verified=? WHERE id=?').run(b.name,b.description,b.category,Number(b.lat),Number(b.lng),Number(b.rating||0),b.image||'',Number(b.verified??1),q.params.id);s.json({success:true})});
app.delete('/api/locations/:id',auth,admin,(q,s)=>{db.prepare('DELETE FROM locations WHERE id=?').run(q.params.id);s.json({success:true})});
app.get('/api/accommodations',(q,s)=>{let rows=db.prepare('SELECT * FROM accommodations WHERE active=1 ORDER BY rating DESC').all();if(q.query.type)rows=rows.filter(x=>x.type===q.query.type);s.json({success:true,data:rows.map(x=>{let images=[];try{images=JSON.parse(x.images||'[]')}catch(_){}return {...x,images}})})});
app.post('/api/reviews',auth,(q,s)=>{const b=q.body||{};const locationId=b.location_id||b.reviewable_id;const rating=Number(b.rating);if(!locationId||!Number.isInteger(rating)||rating<1||rating>5)return s.status(422).json({success:false,message:'location_id and rating 1-5 are required'});if(!db.prepare('SELECT 1 FROM locations WHERE id=?').get(locationId))return s.status(404).json({success:false,message:'Location not found'});const r={id:randomUUID(),user_id:q.user.sub,location_id:locationId,rating,comment:String(b.comment||'').slice(0,2000),created_at:now()};db.prepare('INSERT INTO reviews VALUES(?,?,?,?,?,?)').run(...Object.values(r));const avg=db.prepare('SELECT AVG(rating) avg FROM reviews WHERE location_id=?').get(locationId).avg||0;db.prepare('UPDATE locations SET rating=? WHERE id=?').run(Number(avg.toFixed(1)),locationId);s.status(201).json({success:true,data:r})});
app.get('/api/reviews',(q,s)=>{let rows=db.prepare('SELECT r.*,u.name FROM reviews r LEFT JOIN users u ON u.id=r.user_id ORDER BY r.created_at DESC').all();const locationId=q.query.location_id||q.query.reviewable_id;if(locationId)rows=rows.filter(x=>x.location_id===locationId);s.json({success:true,data:rows.map(x=>({...x,user:{full_name:x.name}}))});});
app.get('/api/bookings',auth,(q,s)=>{const rows=db.prepare('SELECT b.*,a.name accommodation_name FROM bookings b LEFT JOIN accommodations a ON a.id=b.accommodation_id WHERE b.user_id=? ORDER BY b.created_at DESC').all(q.user.sub);s.json({success:true,data:rows.map(b=>({...b,check_in:b.date,check_out:new Date(new Date(b.date).getTime()+b.nights*86400000).toISOString().slice(0,10),total_price:b.total,guests:b.guests||1,accommodation:{name:b.accommodation_name}}))});});
app.post('/api/bookings',auth,(q,s)=>{const b=q.body||{};const date=b.date||b.check_in;if(!date||!b.accommodation_id)return s.status(422).json({success:false,message:'accommodation_id and date are required'});const nights=Math.max(1,Math.min(365,Number(b.nights||1)));const accommodation=db.prepare('SELECT price FROM accommodations WHERE id=? AND active=1').get(b.accommodation_id);if(!accommodation)return s.status(404).json({success:false,message:'Accommodation not found or not available'});const fee=Number(db.prepare("SELECT value FROM settings WHERE key='booking_fee'").get()?.value||0);const total=Number(b.total ?? ((accommodation?.price||0)*nights));const guests=Math.max(1,Math.min(50,Number(b.guests||1)));const r={id:randomUUID(),user_id:q.user.sub,accommodation_id:b.accommodation_id,date,nights,total,guests,status:'confirmed',payment_status:'unpaid',fee,created_at:now()};db.prepare('INSERT INTO bookings(id,user_id,accommodation_id,date,nights,total,guests,status,payment_status,fee,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(r.id,r.user_id,r.accommodation_id,r.date,r.nights,r.total,r.guests,r.status,r.payment_status,r.fee,r.created_at);s.status(201).json({success:true,data:r})});
app.post('/api/bookings/:id/pay',auth,(q,s)=>{const b=db.prepare('SELECT id,payment_status FROM bookings WHERE id=? AND user_id=?').get(q.params.id,q.user.sub);if(!b)return s.status(404).json({success:false,message:'Booking not found'});if(b.payment_status==='paid')return s.json({success:true,data:{payment_status:'paid'}});db.prepare("UPDATE bookings SET payment_status='paid',status='confirmed' WHERE id=? AND user_id=?").run(q.params.id,q.user.sub);s.json({success:true,data:{payment_status:'paid'}})});
app.get('/api/favorites',auth,(q,s)=>s.json({success:true,data:db.prepare('SELECT l.* FROM favorites f JOIN locations l ON l.id=f.location_id WHERE f.user_id=?').all(q.user.sub)}));
app.post('/api/favorites/:id',auth,(q,s)=>{db.prepare('INSERT OR IGNORE INTO favorites VALUES(?,?)').run(q.user.sub,q.params.id);s.json({success:true})});app.delete('/api/favorites/:id',auth,(q,s)=>{db.prepare('DELETE FROM favorites WHERE user_id=? AND location_id=?').run(q.user.sub,q.params.id);s.json({success:true})});
app.post('/api/ai/chat',auth,async(q,s)=>{try{const r=await fetch((process.env.OLLAMA_URL||'http://127.0.0.1:11434')+'/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:process.env.OLLAMA_MODEL||'llama3:latest',stream:false,messages:[{role:'system',content:'You are Kurdistan Tourism AI. Give practical tourism advice for Kurdistan Region of Iraq. Respond in the user language.'},{role:'user',content:String(q.body?.message||'')} ]})});const j=await r.json();s.json({success:true,data:{reply:j.message?.content||'AI unavailable'}})}catch(e){s.json({success:true,data:{reply:'AI is not connected. Start Ollama and try again.'}})} });
app.get('/api/weather',(q,s)=>s.json({success:true,data:{provider:'Open-Meteo',note:'Connect the frontend to Open-Meteo for live weather using lat/lng.'}}));
app.listen(process.env.PORT||8000,()=>console.log('Kurdistan Tourism API PRO running on '+(process.env.PORT||8000)));
