const express=require('express');
const cors=require('cors');
const dotenv=require('dotenv');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const {randomUUID}=require('crypto');
const {q}=require('./db');
const {initDb}=require('./schema');
dotenv.config();

const app=express();
const PORT=Number(process.env.PORT||8000);
if(process.env.NODE_ENV==='production'&&(!process.env.JWT_SECRET||process.env.JWT_SECRET.length<32))throw new Error('JWT_SECRET must be at least 32 characters in production');
app.use(cors({origin:process.env.CORS_ORIGIN?process.env.CORS_ORIGIN.split(',').map(x=>x.trim()):true}));
app.use(express.json({limit:'12mb'}));

const now=()=>new Date().toISOString();
const safeUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,created_at:u.created_at});
function token(u){return jwt.sign({sub:u.id,role:u.role,email:u.email},process.env.JWT_SECRET||'dev-secret',{expiresIn:'30d'});}
async function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({success:false,message:'Authentication required'});const p=jwt.verify(h.slice(7),process.env.JWT_SECRET||'dev-secret');const r=await q('SELECT id,name,email,role,banned,created_at FROM users WHERE id=$1',[p.sub]);if(!r.rows[0]||r.rows[0].banned)return res.status(401).json({success:false,message:'Account disabled'});req.user=r.rows[0];next();}catch(e){res.status(401).json({success:false,message:'Invalid token'});}}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({success:false,message:'Admin only'});next();}
const bodyRows=r=>r.rows.map(x=>{if(typeof x.images==='string'){try{x.images=JSON.parse(x.images)}catch{}}return x});

app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({success:true,status:'online',database:'postgresql',version:'13.0.0'});}catch(e){res.status(503).json({success:false,status:'database_unavailable'});}});
app.post('/api/auth/register',async(req,res)=>{const {name,email,password}=req.body||{};if(!name||!email||!password||password.length<6)return res.status(422).json({success:false,message:'Name, email and password (6+) are required'});try{const u={id:randomUUID(),name:String(name).trim(),email:String(email).trim().toLowerCase(),password:await bcrypt.hash(password,10),role:'user'};const r=await q('INSERT INTO users(id,name,email,password,role) VALUES($1,$2,$3,$4,$5) RETURNING id,name,email,role,created_at',[u.id,u.name,u.email,u.password,u.role]);res.json({success:true,data:{user:safeUser(r.rows[0]),token:token(r.rows[0])}});}catch(e){res.status(409).json({success:false,message:'Email already exists'});}});
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body||{};const r=await q('SELECT * FROM users WHERE lower(email)=lower($1)',[email||'']);const u=r.rows[0];if(!u||!(await bcrypt.compare(password||'',u.password)))return res.status(401).json({success:false,message:'Invalid credentials'});if(u.banned)return res.status(403).json({success:false,message:'Account disabled'});res.json({success:true,data:{user:safeUser(u),token:token(u)}});});
app.get('/api/auth/me',auth,(req,res)=>res.json({success:true,data:safeUser(req.user)}));
app.post('/api/auth/logout',auth,(req,res)=>res.json({success:true}));

app.get('/api/locations',async(req,res)=>{let sql='SELECT * FROM locations WHERE verified=true';const p=[];if(req.query.category){p.push(req.query.category);sql+=' AND category=$'+p.length;}if(req.query.search){p.push('%'+String(req.query.search).toLowerCase()+'%');sql+=' AND (lower(name) LIKE $'+p.length+' OR lower(description) LIKE $'+p.length+' OR lower(category) LIKE $'+p.length+')';}sql+=' ORDER BY rating DESC';const r=await q(sql,p);let rows=bodyRows(r);const lat=Number(req.query.near_lat),lng=Number(req.query.near_lng),radius=Number(req.query.radius_m||10000);if(Number.isFinite(lat)&&Number.isFinite(lng)){const R=6371000,rad=x=>x*Math.PI/180;rows=rows.map(x=>({...x,distance_m:2*R*Math.asin(Math.sqrt(Math.sin((rad(x.lat)-rad(lat))/2)**2+Math.cos(rad(lat))*Math.cos(rad(x.lat))*Math.sin((rad(x.lng)-rad(lng))/2)**2))})).filter(x=>x.distance_m<=radius).sort((a,b)=>a.distance_m-b.distance_m);}res.json({success:true,data:rows});});
app.get('/api/locations/:id',async(req,res)=>{const r=await q('SELECT * FROM locations WHERE id=$1',[req.params.id]);r.rows[0]?res.json({success:true,data:bodyRows(r)[0]}):res.status(404).json({success:false,message:'Location not found'});});

app.get('/api/accommodations',async(req,res)=>{const r=await q('SELECT * FROM accommodations WHERE active=true ORDER BY rating DESC');res.json({success:true,data:bodyRows(r)});});
app.get('/api/reviews',async(req,res)=>{let sql='SELECT r.*,u.name FROM reviews r LEFT JOIN users u ON u.id=r.user_id';const p=[];if(req.query.location_id){p.push(req.query.location_id);sql+=' WHERE r.location_id=$1';}sql+=' ORDER BY r.created_at DESC';const r=await q(sql,p);res.json({success:true,data:r.rows.map(x=>({...x,user:{full_name:x.name}}))});});
app.post('/api/reviews',auth,async(req,res)=>{const b=req.body||{},locationId=b.location_id||b.reviewable_id,rating=Number(b.rating);if(!locationId||!Number.isInteger(rating)||rating<1||rating>5)return res.status(422).json({success:false,message:'location_id and rating 1-5 are required'});const id=randomUUID();await q('INSERT INTO reviews(id,user_id,location_id,rating,comment) VALUES($1,$2,$3,$4,$5)',[id,req.user.id,locationId,rating,String(b.comment||'').slice(0,2000)]);await q('UPDATE locations SET rating=COALESCE((SELECT ROUND(AVG(rating)::numeric,1) FROM reviews WHERE location_id=$1),0) WHERE id=$1',[locationId]);res.status(201).json({success:true,data:{id,user_id:req.user.id,location_id:locationId,rating,comment:String(b.comment||'').slice(0,2000),created_at:now()}});});

app.get('/api/bookings',auth,async(req,res)=>{const r=await q('SELECT b.*,a.name accommodation_name FROM bookings b LEFT JOIN accommodations a ON a.id=b.accommodation_id WHERE b.user_id=$1 ORDER BY b.created_at DESC',[req.user.id]);res.json({success:true,data:r.rows.map(b=>({...b,check_in:b.date,check_out:new Date(new Date(b.date).getTime()+b.nights*86400000).toISOString().slice(0,10),total_price:b.total,accommodation:{name:b.accommodation_name}}))});});
app.post('/api/bookings',auth,async(req,res)=>{const b=req.body||{},date=b.date||b.check_in,nights=Math.max(1,Math.min(365,Number(b.nights||1))),guests=Math.max(1,Math.min(50,Number(b.guests||1)));if(!date||!b.accommodation_id)return res.status(422).json({success:false,message:'accommodation_id and date are required'});const a=await q('SELECT price FROM accommodations WHERE id=$1 AND active=true',[b.accommodation_id]);if(!a.rows[0])return res.status(404).json({success:false,message:'Accommodation not found or not available'});const st=await q("SELECT value FROM settings WHERE key='booking_fee'");const fee=Number(st.rows[0]?.value||0),total=Number(a.rows[0].price||0)*nights,id=randomUUID();const r=await q('INSERT INTO bookings(id,user_id,accommodation_id,date,nights,total,guests,status,payment_status,fee) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[id,req.user.id,b.accommodation_id,date,nights,total,guests,'confirmed','unpaid',fee]);res.status(201).json({success:true,data:r.rows[0]});});
app.post('/api/bookings/:id/pay',auth,async(req,res)=>{const r=await q("UPDATE bookings SET payment_status='paid',status='confirmed' WHERE id=$1 AND user_id=$2 RETURNING id,payment_status",[req.params.id,req.user.id]);r.rows[0]?res.json({success:true,data:r.rows[0]}):res.status(404).json({success:false,message:'Booking not found'});});
app.get('/api/favorites',auth,async(req,res)=>{const r=await q('SELECT l.* FROM favorites f JOIN locations l ON l.id=f.location_id WHERE f.user_id=$1',[req.user.id]);res.json({success:true,data:bodyRows(r)});});
app.post('/api/favorites/:id',auth,async(req,res)=>{await q('INSERT INTO favorites(user_id,location_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,req.params.id]);res.json({success:true});});
app.delete('/api/favorites/:id',auth,async(req,res)=>{await q('DELETE FROM favorites WHERE user_id=$1 AND location_id=$2',[req.user.id,req.params.id]);res.json({success:true});});

app.get('/api/hero',async(req,res)=>{const s=await q("SELECT value FROM settings WHERE key='hero_interval_sec'");const r=await q('SELECT image FROM hero_images WHERE active=true ORDER BY sort_order,created_at');res.json({success:true,data:{interval_sec:Number(s.rows[0]?.value||5),images:r.rows.map(x=>x.image)}});});
app.get('/api/ads',async(req,res)=>{const r=await q('SELECT id,title,company,image,link,starts_at,ends_at FROM ads WHERE active=true AND starts_at<=NOW() AND ends_at>=NOW() ORDER BY starts_at DESC');res.json({success:true,data:r.rows});});
app.get('/api/emergency',async(req,res)=>{const r=await q('SELECT id,label,label_ku,label_ar,phone FROM emergency_contacts ORDER BY sort_order,created_at');res.json({success:true,data:r.rows});});
app.get('/api/notifications',async(req,res)=>{const r=await q('SELECT id,title,body,created_at FROM notifications ORDER BY created_at DESC LIMIT 50');res.json({success:true,data:r.rows});});
app.get('/api/settings/public',async(req,res)=>{const r=await q('SELECT key,value FROM settings');const x=Object.fromEntries(r.rows.map(a=>[a.key,a.value]));res.json({success:true,data:{booking_fee:Number(x.booking_fee||0),currency:x.currency||'IQD',hero_interval_sec:Number(x.hero_interval_sec||5)}});});
app.get('/api/categories',(req,res)=>res.json({success:true,data:{locations:['historical','archaeological','cultural','museum','market','city','mountain','lake','waterfall','cave','nature','park','heritage','other'],accommodations:['hotel','house','cabin','chalet']}}));

app.get('/api/admin/stats',auth,admin,async(req,res)=>{const one=async(s,p=[])=>{const r=await q(s,p);return r.rows[0]};res.json({success:true,data:{users:Number((await one('SELECT count(*) c FROM users')).c),locations:Number((await one('SELECT count(*) c FROM locations')).c),accommodations:Number((await one('SELECT count(*) c FROM accommodations')).c),bookings:Number((await one('SELECT count(*) c FROM bookings')).c),reviews:Number((await one('SELECT count(*) c FROM reviews')).c)}});});
app.get('/api/admin/users',auth,admin,async(req,res)=>{const r=await q('SELECT id,name,email,role,banned,created_at FROM users ORDER BY created_at DESC');res.json({success:true,data:r.rows});});
app.get('/api/admin/bookings',auth,admin,async(req,res)=>{const r=await q('SELECT b.*,u.name user_name,u.email user_email,a.name accommodation_name,a.type accommodation_type FROM bookings b LEFT JOIN users u ON u.id=b.user_id LEFT JOIN accommodations a ON a.id=b.accommodation_id ORDER BY b.created_at DESC');res.json({success:true,data:r.rows});});
app.put('/api/admin/bookings/:id',auth,admin,async(req,res)=>{const {status,payment_status}=req.body||{};const r=await q('UPDATE bookings SET status=COALESCE($1,status),payment_status=COALESCE($2,payment_status) WHERE id=$3 RETURNING *',[status||null,payment_status||null,req.params.id]);r.rows[0]?res.json({success:true,data:r.rows[0]}):res.status(404).json({success:false,message:'Not found'});});

async function start(){await initDb();const adminEmail=process.env.ADMIN_EMAIL||'admin@kurdistantourism.local';const adminPassword=process.env.ADMIN_PASSWORD||'ChangeMe123!';const r=await q('SELECT id FROM users WHERE lower(email)=lower($1)',[adminEmail]);if(!r.rows[0])await q('INSERT INTO users(id,name,email,password,role) VALUES($1,$2,$3,$4,$5)',[randomUUID(),'Administrator',adminEmail,await bcrypt.hash(adminPassword,10),'admin']);app.listen(PORT,'0.0.0.0',()=>console.log('Kurdistan Tourism PostgreSQL API running on '+PORT));}
start().catch(e=>{console.error('Startup failed:',e);process.exit(1);});
